import type { KnowledgeRule } from "@/lib/knowledge-engine";

export const PROMOTION_COMMON_KNOWLEDGE: KnowledgeRule = {
  key: "promotion:common:attention-trust-action",
  kind: "combination",
  label: "販促共通：読まれる・信頼される・行動しやすい構成",
  priority: 98,
  source: "seed",
  tasks: ["promotion"],
  guidance: [
    "最初の数行で『誰のどんな悩みに役立つか』『何が分かるか』『先に結論』のうち必要な要素を示し、前置きを長くしない",
    "タイトル・冒頭・本文・CTAの約束を一致させ、クリック後に内容が違うと感じさせる釣り表現を避ける",
    "抽象的な『便利・すごい・簡単』だけで訴求せず、具体的な利用場面、操作、判断基準、得られる成果物で価値を説明する",
    "1つの段落・1つの投稿で伝える中心メッセージを絞り、重要度の低い情報を詰め込みすぎない",
    "見出し、短い段落、箇条書き、番号付き手順を使い、流し読みでも論点と次の行動が分かる構成にする",
    "読者の不安や反論を先回りし、向いている人、向いていない人、制限、注意点を必要に応じて明記する",
    "CTAは目的に合わせて1つを主軸にし、価値説明より先に押し売りしない",
    "スクリーンショットは装飾ではなく『主張の根拠』『操作の理解』『利用イメージ』のいずれかを担う画像だけを使う",
    "同じテーマでも切り口を変え、悩み解決、機能紹介、使い方、比較判断、開発背景、FAQなどをローテーションする",
    "公開後に改善する場合は、媒体で確認できる表示・クリック・保存・返信等の実データを使い、未確認のアルゴリズム推測ではなく仮説として改善する",
  ],
  deliverables: [
    "読者が止まりやすいタイトルまたは冒頭フック",
    "流し読みできる構成",
    "具体例・手順・判断材料",
    "スクリーンショット配置計画",
    "目的に合う自然なCTA",
    "公開前の事実・誇張チェック",
  ],
  cautions: [
    "インプレッション、クリック、保存、購入、フォロー増加を保証しない",
    "刺激の強い言葉を増やすだけで読まれると判断しない",
    "存在しない体験談、利用者の声、数字、効果、比較結果を作らない",
    "プラットフォームのアルゴリズムや表示ロジックを最新確認なしに固定ルールとして断定しない",
    "読者の不安を煽るだけの恐怖訴求や、本文で回収できない誇張タイトルを使わない",
  ],
  sourceUrls: [
    "https://note.com/help/pg/howto",
    "https://business.x.com/en/basics/get-your-business-started-with-x",
    "https://about.fb.com/news/2024/10/find-your-community-with-new-threads-educational-insights/",
    "https://about.fb.com/news/2024/10/best-practices-education-hub-creators-instagram/",
  ],
  sourceSummary:
    "note・X・Threads・Instagramの公式/運営公式ガイドで、読者価値の明確化、自然で簡潔な表現、会話・反応を生む設計、媒体別のBest Practicesと計測改善を確認。成果保証ではなく、読者理解と実データ改善を共通Knowledge化。",
};

export const PROMOTION_PUBLICATION_KNOWLEDGE: KnowledgeRule[] = [
  {
    key: "promotion:publication:note",
    kind: "publication",
    label: "note",
    aliases: ["NOTE"],
    priority: 96,
    source: "seed",
    tasks: ["promotion"],
    guidance: [
      "タイトルは記事内容が一目で分かり、読後に得られるものを想像できる表現を優先する",
      "本文を書き終えた内容とタイトルを照合し、本文にない強い約束をタイトルへ足さない",
      "導入では読者の悩みと記事を読む理由を短く整理し、最初の見出しまでを引き延ばさない",
      "見出しだけを追っても記事の流れが分かるよう、各見出しに役割を持たせる",
      "長文では説明→具体例→判断基準→次の行動を繰り返し、同じ結論の言い換えで文字数を増やさない",
      "スクショは機能説明や手順の直後に置き、画像を見るだけでも何を確認すべきか分かる短いキャプションを付ける",
      "販売前は開発・テスト状況を誠実に共有し、販売開始後も無料部分だけで購入判断に必要な情報を隠しすぎない",
    ],
    deliverables: ["タイトル候補", "読みやすい見出し構成", "完成記事", "本文内スクショ挿入位置", "キャプション", "公開前チェック"],
    cautions: [
      "内容と無関係な数字・煽り文句をタイトルへ追加しない",
      "ユーザーが入力していない体験談を『自分が試した』形式で作らない",
    ],
    sourceUrls: ["https://note.com/help/pg/howto", "https://note.com/qa/info"],
    sourceSummary:
      "note公式の創作ヒントと公式Q&Aで、内容が伝わるタイトル、読後価値が想像できるタイトル、読みやすい記事、見出し画像等の基本を確認。",
  },
  {
    key: "promotion:publication:brain",
    kind: "publication",
    label: "Brain",
    aliases: ["brain", "ブレイン"],
    priority: 96,
    source: "seed",
    tasks: ["promotion"],
    guidance: [
      "購入・利用判断に必要な『誰向けか』『何が得られるか』『前提条件』『できないこと』『注意点』を具体化する",
      "価格や機能を並べる前に、読者の課題とAASがどの場面で役立つのかを利用シーンで説明する",
      "価値の説明には確認済み機能、画面、手順、成果物を使い、根拠のない権威づけや希少性を作らない",
      "購入前の疑問をFAQとして先回りし、比較検討時に残る不安を減らす",
      "スクショは『この機能がある』という主張の直後や利用フローの節目に置き、何を裏付ける画像かを明記する",
      "販売前は購入導線を作らず、先行案内・開発状況・公開予定として構成する",
    ],
    deliverables: ["購入判断用の価値整理", "機能根拠", "利用イメージ", "FAQ", "スクショ根拠計画", "CTA"],
    cautions: [
      "ランキング、販売数、レビュー、紹介報酬、値引き等を未確認で本文へ足さない",
      "高単価・限定・残りわずか等の希少性を事実確認なしに作らない",
    ],
    sourceUrls: ["https://brain-market.com/", "https://media.brain-market.com/category/contents/"],
    sourceSummary:
      "Brain公式サイトと公式メディアのコンテンツ販売領域を確認。AASでは販売実績の模倣ではなく、購入判断に必要な価値・根拠・FAQ・透明性をKnowledge化。",
  },
  {
    key: "promotion:publication:tips",
    kind: "publication",
    label: "Tips",
    aliases: ["tips", "TIPS"],
    priority: 96,
    source: "seed",
    tasks: ["promotion"],
    guidance: [
      "結論までの距離を短くし、『何ができるか』『どうやるか』を早い段階で示す",
      "手順は番号付きにし、各ステップで入力・操作・確認結果が分かる粒度にする",
      "読者が実行時に迷う分岐、失敗しやすい点、チェック項目を本文へ入れる",
      "抽象論よりテンプレート、チェックリスト、具体例、判断基準など再利用できる成果物を優先する",
      "スクショは該当する操作ステップの直後に置き、画面全体ではなく押す場所・確認する場所が分かる範囲を指定する",
      "CTAの前に、記事だけで最低1つ実行できる具体的価値を残す",
    ],
    deliverables: ["実行手順", "チェックリスト", "具体例", "スクショ付き操作位置", "公開前チェック"],
    cautions: [
      "手順を省略して『簡単』とだけ表現しない",
      "Tips側の現在仕様、価格、キャンペーン、販売条件を未確認で固定化しない",
    ],
    sourceUrls: ["https://tips.jp/", "https://tips.jp/news"],
    sourceSummary:
      "Tips公式サイト/お知らせを現行プラットフォーム確認先として設定。変動仕様は固定せず、AASでは実践性・再利用性・手順明確化を中心にKnowledge化。",
  },
  {
    key: "promotion:publication:x",
    kind: "publication",
    label: "X",
    aliases: ["x", "Twitter", "twitter"],
    priority: 96,
    source: "seed",
    tasks: ["promotion"],
    guidance: [
      "冒頭1〜2行で対象読者と中心メッセージが分かるようにし、前置きを置かない",
      "1投稿1メッセージを基本にし、機能を複数紹介する場合は最重要の1つへ絞るか投稿を分ける",
      "新規層向けでは専門用語を減らし、誰に何の価値があるかを平易に書く",
      "売り込みだけにせず、投稿単体でも役立つ気づき・具体例・小さなノウハウを含める",
      "画像を使う場合は投稿本文の主張を一目で補強する1枚を優先し、文字が読めない縮小全画面を避ける",
      "目的が会話なら質問、送客ならリンク、継続接触ならフォローなど、CTAを1つ明確にする",
      "ハッシュタグを使う場合は関連性の高いものだけに絞り、タグの羅列で本文を弱くしない",
    ],
    deliverables: ["冒頭フック", "短い価値提供", "明確なCTA", "添付スクショ指示", "複数切り口案"],
    cautions: [
      "インプレッションを増やす万能な投稿時間・投稿形式・ハッシュタグ数があると断定しない",
      "トレンドへ無理に便乗してAASと無関係な投稿を作らない",
    ],
    sourceUrls: [
      "https://business.x.com/en/basics/get-your-business-started-with-x",
      "https://business.x.com/ja/blog/jp-business-organic-tweet-tips",
      "https://business.x.com/ja/blog/do-dont-twitter-images",
    ],
    sourceSummary:
      "X公式ビジネスガイドで、簡潔で自然な投稿、対象読者と目的の明確化、有益性、視覚素材、明確なCTA、関連性のあるハッシュタグ運用を確認。",
  },
  {
    key: "promotion:publication:threads",
    kind: "publication",
    label: "Threads",
    aliases: ["threads", "スレッズ"],
    priority: 96,
    source: "seed",
    tasks: ["promotion"],
    guidance: [
      "広告文より会話として読める自然な書き出しを優先し、読者が返信しやすい余白を残す",
      "共感、気づき、開発背景、問いかけのいずれかを起点にし、投稿ごとに話題を1つへ絞る",
      "Xの文章をそのまま流用せず、Threads向けに背景説明や会話性を足して書き直す",
      "写真・スクショを添える場合は、画像だけに説明を任せず本文で何を見る画像か文脈を与える",
      "反応を求める場合は答えやすい具体的な質問を使い、露骨なエンゲージメント稼ぎの文句を避ける",
      "開発途中の内容は完成品のように見せず、『試していること』『分かったこと』『次に直すこと』を会話調で分ける",
    ],
    deliverables: ["会話的な投稿", "返信しやすい問い", "画像の文脈説明", "添付順", "複数切り口案"],
    cautions: [
      "返信数や表示回数が必ず増えると保証しない",
      "公式の過去データを、現在の全アカウントへ同じ結果が出る固定アルゴリズムとして扱わない",
    ],
    sourceUrls: ["https://about.fb.com/news/2024/10/find-your-community-with-new-threads-educational-insights/"],
    sourceSummary:
      "Meta公式Threads教育リソースで、会話を生む投稿、返信、文脈付きメディア、Threads向けオリジナルコンテンツ等の考え方を確認。数値は保証に使わず制作原則へ抽象化。",
  },
  {
    key: "promotion:publication:instagram",
    kind: "publication",
    label: "Instagram",
    aliases: ["instagram", "インスタ", "インスタグラム"],
    priority: 96,
    source: "seed",
    tasks: ["promotion"],
    guidance: [
      "カルーセルは1枚目で『誰向け・何が分かる』を明確にし、2枚目以降を1スライド1メッセージで組み立てる",
      "課題→解決の考え方→AAS機能→実画面→使い方→まとめの順など、スワイプする理由が続く流れを作る",
      "スクショはそのまま縮小せず、スマホで読める範囲へトリミングし、必要なら注目箇所を文章で説明する",
      "キャプションは画像だけで伝わらない背景・補足・注意点を担わせ、カルーセル本文の単純な全文コピーにしない",
      "保存して後で見返す価値がある場合は、チェックリスト、手順、比較軸、設定ポイントを含める",
      "CTAは保存、フォロー、詳細確認など今回の目的に合う1つを主軸にする",
      "投稿後はProfessional Dashboard等の利用可能なInsightsを見て、どの内容が読者に響いたかを実データで改善する",
    ],
    deliverables: ["カルーセル構成", "1枚目フック", "スライド別メッセージ", "キャプション", "縦長スクショ計画", "CTA"],
    cautions: [
      "特定フォーマットを使えば必ずリーチが伸びると断定しない",
      "流行音源・ハッシュタグ・投稿頻度など変動要素を普遍ルールとして固定しない",
    ],
    sourceUrls: [
      "https://about.fb.com/news/2024/10/best-practices-education-hub-creators-instagram/",
      "https://about.fb.com/news/2023/08/music-and-collabs-on-instagram/",
    ],
    sourceSummary:
      "Instagram公式Best PracticesでCreation・Engagement・Reach・Monetization・Guidelinesを分けて学び、個別Insightsで改善する方針を確認。カルーセル機能の公式案内も参照。",
  },
];
