import type { SideHustleDefinition } from "@/features/side-hustles/types";
import { promptLines, sideField, sideOption } from "@/features/side-hustles/definition-helpers";

export const SALES_SIDE_HUSTLES: readonly SideHustleDefinition[] = [
  {
    slug: "affiliate",
    title: "アフィリエイト",
    category: "販売・収益化",
    summary: "読者の購入判断を助ける比較軸、一次情報確認、記事構成、CTAを広告表現に配慮して設計します。",
    knowledgeTask: "sidejob_affiliate",
    recommendedAi: "gemini",
    fields: [
      sideField("channel", "主な集客先", "読者がどこから比較情報へ来るかを選びます。", "basic", "例：メールマガジン", [
        sideOption("blog", "ブログ・SEO"), sideOption("note", "note"), sideOption("x", "X"),
        sideOption("instagram", "Instagram"), sideOption("youtube", "YouTube"),
      ]),
      sideField("product_type", "紹介ジャンル", "比較項目と確認すべき情報源を変えます。", "basic", "例：オンライン英会話", [
        sideOption("software", "ソフトウェア・Webサービス"), sideOption("device", "ガジェット・家電"),
        sideOption("subscription", "サブスクリプション"), sideOption("education", "スクール・学習"),
        sideOption("daily_goods", "日用品・生活用品"),
      ]),
      sideField("reader_stage", "読者の検討段階", "購入意欲を決めつけず段階に合わせます。", "basic", "例：候補を2社まで絞っている", [
        sideOption("problem", "悩みを認識した段階"), sideOption("research", "選択肢を調査中"),
        sideOption("compare", "複数候補を比較中"), sideOption("final", "最終確認中"),
        sideOption("existing", "現在利用中で乗り換え検討"),
      ]),
      sideField("comparison_style", "比較方法", "不公平な比較を避け、共通軸を固定します。", "detail", "例：初心者用途だけに絞って比較", [
        sideOption("single_review", "1商品を深掘り"), sideOption("two_compare", "2商品比較"),
        sideOption("multi_compare", "3つ以上を比較"), sideOption("use_case", "用途別おすすめ整理"),
        sideOption("alternative", "代替候補の整理"),
      ]),
      sideField("evidence", "使える確認情報", "実体験の有無を明確に分けます。", "detail", "例：公式仕様書と公開料金表のみ", [
        sideOption("official_only", "公式情報のみ"), sideOption("own_use", "自分の利用経験あり"),
        sideOption("owned_product", "実物を所有・確認済み"), sideOption("public_reviews", "第三者レビューも参考にする"),
        sideOption("mixed", "公式＋自分の経験＋外部情報"),
      ], true),
      sideField("cta", "読者にしてほしい次の行動", "強い購入誘導より判断支援を優先します。", "detail", "例：無料トライアル条件を公式で確認", [
        sideOption("official_check", "公式条件を確認"), sideOption("trial", "無料体験・試用を検討"),
        sideOption("compare", "比較表で再確認"), sideOption("buy", "購入ページを確認"),
        sideOption("save", "後で比較できるよう保存"),
      ]),
    ],
    promptTemplate: promptLines(
      "あなたはアフィリエイト編集者兼ファクトチェック担当です。",
      "広告収益より先に、読者が誤解なく購入判断できる比較コンテンツを設計してください。",
      "",
      "【条件】",
      "集客先: {{channel}}",
      "紹介ジャンル: {{product_type}}",
      "読者の検討段階: {{reader_stage}}",
      "比較方法: {{comparison_style}}",
      "利用できる根拠: {{evidence}}",
      "CTA: {{cta}}",
      "",
      "【必須成果物】",
      "1. 読者が比較前に整理すべき条件",
      "2. 全候補に共通で適用する比較軸",
      "3. 公式一次情報で確認する項目とURL種別",
      "4. 「事実」「自分の経験」「第三者評価」を分ける書き方",
      "5. 記事/投稿の構成",
      "6. 比較表の列",
      "7. 向いている人 / 向かない可能性がある人",
      "8. 価格・在庫・キャンペーン等の更新確認チェック",
      "9. 広告・アフィリエイトであることを踏まえた自然なCTA",
      "10. 公開直前チェックリスト",
      "",
      "未確認の価格・評価・ランキング・在庫・キャンペーンを事実として補完しないでください。",
      "利用していない商品を「使った」と書かないでください。"
    ),
  },
  {
    slug: "resale",
    title: "物販・フリマ販売",
    category: "販売・収益化",
    summary: "商品状態、説明、撮影、価格判断材料、発送・購入前注意を整理し、誤解の少ない出品を作ります。",
    knowledgeTask: "sidejob_resale",
    recommendedAi: "chatgpt",
    fields: [
      sideField("marketplace", "販売先", "販売先によって文面・購入者期待を調整します。", "basic", "例：自社EC、海外マーケット", [
        sideOption("mercari", "メルカリ"), sideOption("rakuma", "ラクマ"),
        sideOption("yahoo", "Yahoo!フリマ / オークション"), sideOption("amazon", "Amazon"),
        sideOption("ec", "自社EC"),
      ]),
      sideField("category", "商品カテゴリ", "状態確認項目をカテゴリに合わせます。", "basic", "例：トレーディングカード", [
        sideOption("fashion", "衣類・ファッション"), sideOption("electronics", "家電・ガジェット"),
        sideOption("hobby", "ゲーム・ホビー"), sideOption("books", "本・メディア"),
        sideOption("home", "生活用品・家具"),
      ]),
      sideField("condition", "確認済みの商品状態", "不明な状態は推測しません。", "basic", "例：外箱に傷、動作確認済み", [
        sideOption("new", "新品・未使用"), sideOption("like_new", "未使用に近い"),
        sideOption("good", "目立つ傷なし"), sideOption("used", "使用感あり"),
        sideOption("damaged", "傷・不具合あり"),
      ], true),
      sideField("inventory", "仕入れ形態", "利益計算や注意点の前提に使います。", "detail", "例：店舗仕入れの中古品", [
        sideOption("own", "自宅の不用品"), sideOption("retail", "店舗仕入れ"),
        sideOption("online", "オンライン仕入れ"), sideOption("handmade", "自作品"),
        sideOption("lot", "まとめ仕入れ"),
      ]),
      sideField("shipping", "発送方針", "梱包・発送前確認を具体化します。", "detail", "例：大型便、購入後に日時調整", [
        sideOption("small", "小型・匿名配送"), sideOption("box", "宅配便"),
        sideOption("fragile", "壊れ物・精密品"), sideOption("large", "大型商品"),
        sideOption("handoff", "対面受渡し"),
      ]),
      sideField("goal", "今回の優先事項", "価格だけでなく販売方針を選びます。", "detail", "例：説明不足による返品を避けたい", [
        sideOption("fast", "早めに売りたい"), sideOption("margin", "利益を重視"),
        sideOption("trust", "購入者の安心を重視"), sideOption("clear_inventory", "在庫整理を重視"),
        sideOption("repeat", "継続販売の型を作りたい"),
      ]),
    ],
    promptTemplate: promptLines(
      "あなたは物販・フリマ出品の編集担当です。",
      "確認済み情報だけを使い、購入者が状態・付属品・発送条件を誤解しにくい出品設計を作ってください。",
      "",
      "【条件】",
      "販売先: {{marketplace}}",
      "商品カテゴリ: {{category}}",
      "商品状態: {{condition}}",
      "仕入れ形態: {{inventory}}",
      "発送方針: {{shipping}}",
      "優先事項: {{goal}}",
      "",
      "【必須成果物】",
      "1. 出品前に追加確認すべき商品情報",
      "2. タイトル候補5案",
      "3. 商品説明テンプレート",
      "4. 状態説明（確認済み / 未確認を分ける）",
      "5. 写真で撮るべき箇所リスト",
      "6. 付属品チェック",
      "7. 梱包・発送前チェック",
      "8. 価格を決める際に入力・確認すべき費用項目",
      "9. 購入前に明記すべき注意事項",
      "10. 継続出品用の再利用テンプレート",
      "",
      "傷、動作状態、購入時期、定価、正規品判定、使用回数など未入力の事実を作らないでください。",
      "販売先の禁止商品・手数料・配送条件など変動する仕様は最新公式情報の確認項目として分けてください。"
    ),
  },
  {
    slug: "skill-sales",
    title: "スキル販売",
    category: "販売・収益化",
    summary: "提供範囲、購入前条件、納品物、修正範囲、サービスページまで一つの販売設計にします。",
    knowledgeTask: "sidejob_skill_sales",
    recommendedAi: "claude",
    fields: [
      sideField("platform", "販売先", "販売ページの見せ方を合わせます。", "basic", "例：自社サイト、SNS経由", [
        sideOption("coconala", "ココナラ"), sideOption("stores", "STORES"),
        sideOption("base", "BASE"), sideOption("direct", "直接販売"),
        sideOption("membership", "会員・コミュニティ向け"),
      ]),
      sideField("service", "提供スキル", "成果物と作業範囲を決めます。", "basic", "例：OBS初期設定サポート", [
        sideOption("writing", "文章作成・編集"), sideOption("design", "画像・デザイン"),
        sideOption("video", "動画編集"), sideOption("consulting", "相談・アドバイス"),
        sideOption("setup", "設定・作業代行"),
      ]),
      sideField("buyer_problem", "購入者の主な困りごと", "機能説明ではなく課題から設計します。", "basic", "例：配信音声の設定方法が分からない", [
        sideOption("time", "時間がない"), sideOption("knowledge", "方法が分からない"),
        sideOption("quality", "品質を上げたい"), sideOption("stuck", "途中で止まっている"),
        sideOption("second_opinion", "第三者に確認してほしい"),
      ], true),
      sideField("delivery", "納品形態", "購入者が受け取るものを具体化します。", "detail", "例：PDF手順書＋30分ビデオ通話", [
        sideOption("file", "ファイル納品"), sideOption("text", "文章・チャット納品"),
        sideOption("call", "通話・相談"), sideOption("work", "作業代行"),
        sideOption("hybrid", "複数形式の組み合わせ"),
      ]),
      sideField("revision", "修正・追加対応", "対応範囲を先に決めます。", "detail", "例：初稿後2回まで", [
        sideOption("none", "修正なし"), sideOption("one", "1回"), sideOption("two", "2回"),
        sideOption("limited", "範囲内で複数回"), sideOption("quote", "内容により追加見積"),
      ]),
      sideField("positioning", "サービスの強み", "実績を捏造せず、提供方法の違いで差別化します。", "detail", "例：初心者向けに画面共有で一緒に設定", [
        sideOption("beginner", "初心者向け"), sideOption("speed", "短時間・迅速"),
        sideOption("careful", "丁寧な確認"), sideOption("template", "テンプレート付き"),
        sideOption("custom", "個別最適化"),
      ], true),
    ],
    promptTemplate: promptLines(
      "あなたはスキル販売サービスの設計者です。",
      "「何でも対応します」ではなく、購入者が安心して購入できる提供範囲と納品条件を明確にしてください。",
      "",
      "【条件】",
      "販売先: {{platform}}",
      "提供スキル: {{service}}",
      "購入者の困りごと: {{buyer_problem}}",
      "納品形態: {{delivery}}",
      "修正・追加対応: {{revision}}",
      "強み: {{positioning}}",
      "",
      "【必須成果物】",
      "1. サービス名候補",
      "2. 一文で分かるサービス概要",
      "3. 対象者 / 対象外",
      "4. 基本料金に含める作業範囲（価格そのものは未指定なら作らない）",
      "5. 納品物",
      "6. 購入前に必ず聞く情報",
      "7. 修正・追加対応のルール",
      "8. 対応できないこと",
      "9. 販売ページ本文",
      "10. FAQ",
      "11. 購入後メッセージのテンプレート",
      "12. 納品前チェックリスト",
      "",
      "入力されていない資格、経験年数、販売件数、評価、顧客実績を作らないでください。"
    ),
  },
  {
    slug: "digital-product",
    title: "デジタル商品・教材販売",
    category: "販売・収益化",
    summary: "購入後の完成状態から逆算し、教材、テンプレート、ワークシート、販売ページまで設計します。",
    knowledgeTask: "sidejob_digital_product",
    recommendedAi: "claude",
    fields: [
      sideField("format", "商品形式", "中身の構造を形式に合わせます。", "basic", "例：Notionテンプレート＋動画", [
        sideOption("pdf", "PDF教材"), sideOption("template", "テンプレート"),
        sideOption("video_course", "動画教材"), sideOption("notion", "Notion・データベース"),
        sideOption("bundle", "複数形式セット"),
      ]),
      sideField("buyer_level", "購入者レベル", "前提知識を揃えます。", "basic", "例：基本操作は分かる中級者", [
        sideOption("zero", "完全初心者"), sideOption("beginner", "基礎は少し分かる"),
        sideOption("intermediate", "経験者"), sideOption("professional", "実務利用者"),
        sideOption("mixed", "幅広いレベル"),
      ]),
      sideField("outcome", "購入後の完成状態", "情報量ではなく完成物で設計します。", "basic", "例：自分用の投稿カレンダーが完成する", [
        sideOption("plan", "自分用の計画が完成"), sideOption("asset", "テンプレート・成果物が完成"),
        sideOption("skill", "手順を一人で実行できる"), sideOption("system", "繰り返し使える仕組みが完成"),
        sideOption("decision", "比較・判断できる状態になる"),
      ], true),
      sideField("scope", "商品のボリューム", "過剰な水増しを避けます。", "detail", "例：全5章＋テンプレート3個", [
        sideOption("mini", "短時間で完了するミニ商品"), sideOption("standard", "標準ボリューム"),
        sideOption("deep", "体系的な教材"), sideOption("reference", "辞書・リファレンス型"),
        sideOption("workbook", "ワーク中心"),
      ]),
      sideField("sales_channel", "販売経路", "購入前情報と導線を調整します。", "detail", "例：Xから自社販売ページ", [
        sideOption("note", "note"), sideOption("tips", "Tips"), sideOption("brain", "Brain"),
        sideOption("store", "EC・販売ページ"), sideOption("sns", "SNS経由"),
      ]),
      sideField("support", "購入後サポート", "無理なサポート約束を避けます。", "detail", "例：購入後7日間の質問フォーム", [
        sideOption("none", "サポートなし"), sideOption("faq", "FAQのみ"),
        sideOption("limited_chat", "期間限定チャット"), sideOption("community", "コミュニティ"),
        sideOption("session", "個別相談付き"),
      ], true),
    ],
    promptTemplate: promptLines(
      "あなたはデジタル商品・教材のプロダクト設計者です。",
      "情報の寄せ集めではなく、購入者が商品を使って具体的な完成状態へ到達できる設計を作ってください。",
      "",
      "【条件】",
      "商品形式: {{format}}",
      "購入者レベル: {{buyer_level}}",
      "購入後の完成状態: {{outcome}}",
      "ボリューム: {{scope}}",
      "販売経路: {{sales_channel}}",
      "購入後サポート: {{support}}",
      "",
      "【必須成果物】",
      "1. 商品コンセプト",
      "2. 対象者 / 前提条件 / 対象外",
      "3. 購入前に見せる完成イメージ",
      "4. 章・モジュール構成",
      "5. 各章で購入者が作る成果物",
      "6. テンプレート・ワークシート一覧",
      "7. つまずきやすい箇所と補助資料",
      "8. 販売ページ構成",
      "9. FAQ",
      "10. サポート範囲",
      "11. 更新が必要になりやすい情報の一覧",
      "12. 商品公開前チェックリスト",
      "",
      "成果保証、架空の販売実績、架空レビュー、未確認の最新仕様は追加しないでください。"
    ),
  },
];
