import type { SideHustleDefinition } from "@/features/side-hustles/types";
import { promptLines, sideField, sideOption } from "@/features/side-hustles/definition-helpers";

export const PRODUCTIVITY_SIDE_HUSTLES: readonly SideHustleDefinition[] = [
  {
    slug: "research",
    title: "リサーチ・事実確認",
    category: "リサーチ・業務効率化",
    summary: "意思決定に必要な問い、一次情報、更新日、比較条件、未確認事項を分けた調査設計を作ります。",
    knowledgeTask: "sidejob_research",
    recommendedAi: "gemini",
    fields: [
      sideField("research_type", "調査タイプ", "調査方法と優先情報源を変えます。", "basic", "例：競合YouTubeチャンネル調査", [
        sideOption("market", "市場調査"), sideOption("competitor", "競合調査"),
        sideOption("product", "商品・サービス比較"), sideOption("fact_check", "事実確認"),
        sideOption("trend", "最新動向調査"),
      ]),
      sideField("decision", "調査で決めたいこと", "調査項目を意思決定へ結び付けます。", "basic", "例：次に作る商品のテーマを3候補へ絞る", [
        sideOption("go_no_go", "実行するか判断"), sideOption("choose", "候補から選ぶ"),
        sideOption("position", "差別化方針を決める"), sideOption("validate", "主張の正しさを確認"),
        sideOption("update", "古い情報を更新"),
      ], true),
      sideField("source_priority", "優先する情報源", "一次情報を優先しつつ用途に合わせます。", "basic", "例：官公庁統計と各社公式料金", [
        sideOption("official", "公式・一次情報を最優先"), sideOption("public_data", "公的統計・データ"),
        sideOption("company", "企業公式情報"), sideOption("academic", "論文・研究"),
        sideOption("mixed", "一次情報＋信頼できる二次情報"),
      ], true),
      sideField("freshness", "必要な最新性", "いつ時点の情報が必要かを決めます。", "detail", "例：2026年9月時点", [
        sideOption("today", "現在・直近"), sideOption("30d", "過去30日"),
        sideOption("year", "過去1年"), sideOption("multi_year", "数年の推移"),
        sideOption("historical", "過去資料も含む"),
      ]),
      sideField("scope", "比較範囲", "調査量を制御します。", "detail", "例：国内主要5社", [
        sideOption("single", "1対象を深掘り"), sideOption("two", "2対象比較"),
        sideOption("five", "最大5対象"), sideOption("broad", "広く探索して絞る"),
        sideOption("sample", "代表例を抽出"),
      ]),
      sideField("deliverable", "最終成果物", "使う場面に合わせて出力を固定します。", "detail", "例：経営判断用1ページ要約", [
        sideOption("brief", "要点サマリー"), sideOption("table", "比較表"),
        sideOption("report", "調査レポート"), sideOption("sources", "根拠URL付き事実一覧"),
        sideOption("decision", "判断材料＋推奨確認事項"),
      ]),
    ],
    promptTemplate: promptLines(
      "あなたはリサーチ設計者兼ファクトチェッカーです。",
      "「検索してそれらしくまとめる」のではなく、意思決定に必要な問いを分解し、根拠の強さと最新性を追跡できる調査計画を作ってください。",
      "",
      "【条件】",
      "調査タイプ: {{research_type}}",
      "決めたいこと: {{decision}}",
      "優先情報源: {{source_priority}}",
      "必要な最新性: {{freshness}}",
      "比較範囲: {{scope}}",
      "成果物: {{deliverable}}",
      "",
      "【必須成果物】",
      "1. 最終判断をするための主要質問",
      "2. 各質問を検証可能な小問へ分解",
      "3. 小問ごとの第一候補の情報源",
      "4. 公開日・更新日・地域・対象プラン等の確認項目",
      "5. 比較条件を揃えるルール",
      "6. 情報が食い違った場合の優先順位",
      "7. 「確認済み / 推定 / 未確認」の記録形式",
      "8. 調査結果の出力フォーマット",
      "9. 追加調査が必要になる条件",
      "10. 最終ファクトチェック手順",
      "",
      "検索結果スニペットだけで断定せず、現在情報と過去情報を混ぜないでください。"
    ),
  },
  {
    slug: "workflow-efficiency",
    title: "業務効率化・SOP化",
    category: "リサーチ・業務効率化",
    summary: "繰り返し作業を入力・処理・確認・保存・例外対応へ分解し、AI活用可能なSOPへ変換します。",
    knowledgeTask: "sidejob_efficiency",
    recommendedAi: "chatgpt",
    fields: [
      sideField("workflow", "効率化する作業", "作業の性質に合わせてSOP構成を変えます。", "basic", "例：毎週のYouTube配信準備", [
        sideOption("content", "コンテンツ制作"), sideOption("research", "調査・情報収集"),
        sideOption("customer", "顧客対応"), sideOption("admin", "事務・管理"),
        sideOption("publishing", "投稿・公開作業"),
      ], true),
      sideField("current_state", "現在の状態", "いきなり自動化せず現在地から改善します。", "basic", "例：手順はあるが人によって順番が違う", [
        sideOption("memory", "頭の中だけ"), sideOption("notes", "メモはある"),
        sideOption("checklist", "チェックリストあり"), sideOption("sop", "既存SOPあり"),
        sideOption("automation", "一部自動化済み"),
      ]),
      sideField("automation", "AI・自動化の範囲", "人が確認すべき工程を残します。", "basic", "例：下書きだけAI、公開は人が確認", [
        sideOption("none", "まず手順化だけ"), sideOption("assist", "AIは補助のみ"),
        sideOption("draft", "AIが下書きを作る"), sideOption("partial", "一部を自動化"),
        sideOption("high", "可能な範囲を大きく自動化"),
      ]),
      sideField("risk", "間違えた時の影響", "確認工程の強さを決めます。", "detail", "例：誤送信すると顧客影響あり", [
        sideOption("low", "低い・やり直せる"), sideOption("medium", "中程度"),
        sideOption("customer", "顧客へ影響"), sideOption("money", "金銭へ影響"),
        sideOption("public", "公開情報へ影響"),
      ], true),
      sideField("frequency", "実行頻度", "テンプレート化の粒度を合わせます。", "detail", "例：月末にまとめて実施", [
        sideOption("daily", "毎日"), sideOption("weekly", "毎週"), sideOption("monthly", "毎月"),
        sideOption("per_project", "案件ごと"), sideOption("irregular", "不定期"),
      ]),
      sideField("output", "欲しい成果物", "実務で再利用できる形式にします。", "detail", "例：Notionへ貼れるSOP", [
        sideOption("checklist", "チェックリスト"), sideOption("sop", "詳細SOP"),
        sideOption("template", "コピペテンプレート"), sideOption("decision_tree", "判断フロー"),
        sideOption("full", "SOP＋テンプレート＋判断フロー"),
      ]),
    ],
    promptTemplate: promptLines(
      "あなたは業務設計・SOP改善担当です。",
      "現状作業を単に短くするのではなく、品質を落とさず再現できる標準手順へ変換してください。",
      "",
      "【条件】",
      "対象作業: {{workflow}}",
      "現在の状態: {{current_state}}",
      "AI・自動化範囲: {{automation}}",
      "ミス時の影響: {{risk}}",
      "実行頻度: {{frequency}}",
      "必要成果物: {{output}}",
      "",
      "【必須成果物】",
      "1. 現在作業を「入力→処理→確認→保存→引継ぎ」に分解",
      "2. なくせる作業 / まとめられる作業 / 自動化候補",
      "3. AIへ渡してよい情報 / 渡さない情報",
      "4. 人が必ず確認する箇所",
      "5. 完成SOP",
      "6. 各工程の完了条件",
      "7. 例外時の判断フロー",
      "8. コピペ用テンプレート",
      "9. 作業時間・品質を改善できたか確認する指標",
      "10. SOPの更新タイミング",
      "",
      "存在しない社内ルール、権限、システム機能、個人情報を勝手に追加しないでください。"
    ),
  },
];
