import type { SideHustleDefinition } from "@/features/side-hustles/types";
import { promptLines, sideField, sideOption } from "@/features/side-hustles/definition-helpers";

export const CONTENT_MEDIA_SIDE_HUSTLES: readonly SideHustleDefinition[] = [
  {
    slug: "content-sales",
    title: "記事・ブログ・コンテンツ販売",
    category: "記事・コンテンツ",
    summary: "無料記事、有料記事、教材型コンテンツの役割を分け、購入後に実行できる価値まで設計します。",
    knowledgeTask: "sidejob_content",
    recommendedAi: "claude",
    fields: [
      sideField("platform", "販売・掲載先", "媒体に合わせて無料部分・有料部分・導線を変えます。", "basic", "例：自社サイト、特定の販売サービス", [
        sideOption("note", "note"), sideOption("tips", "Tips"), sideOption("brain", "Brain"),
        sideOption("blog", "ブログ"), sideOption("newsletter", "ニュースレター"),
      ]),
      sideField("product_type", "作る商品", "完成させたいコンテンツ形態を選びます。", "basic", "例：チェックリスト付き有料記事", [
        sideOption("paid_article", "有料記事"), sideOption("series", "連載・シリーズ"),
        sideOption("guide", "実践ガイド"), sideOption("template_pack", "テンプレート集"),
        sideOption("mini_course", "ミニ教材"),
      ]),
      sideField("buyer_stage", "想定購入者", "購入者の経験レベルに合わせて説明密度を調整します。", "basic", "例：副業を始めて3か月の会社員", [
        sideOption("beginner", "完全初心者"), sideOption("started", "始めたばかり"),
        sideOption("intermediate", "経験者"), sideOption("stuck", "途中で行き詰まっている人"),
        sideOption("comparison", "複数手段を比較中の人"),
      ]),
      sideField("value_type", "購入後に得られる価値", "抽象的なメリットではなく、購入後にできることを基準にします。", "detail", "例：自分用の30日運用表を完成できる", [
        sideOption("decision", "判断できるようになる"), sideOption("complete", "成果物を完成できる"),
        sideOption("operate", "手順どおり実行できる"), sideOption("avoid_mistakes", "失敗を減らせる"),
        sideOption("reuse", "テンプレートを再利用できる"),
      ]),
      sideField("free_paid_boundary", "無料・有料の分け方", "無料部分だけでも価値を残しつつ、有料部分の役割を明確にします。", "detail", "例：無料で判断基準、有料でテンプレートと具体例", [
        sideOption("overview_to_action", "無料＝全体像 / 有料＝実行手順"),
        sideOption("problem_to_template", "無料＝課題整理 / 有料＝テンプレート"),
        sideOption("basic_to_advanced", "無料＝基礎 / 有料＝応用"),
        sideOption("sample_to_full", "無料＝一部サンプル / 有料＝完全版"),
        sideOption("case_to_system", "無料＝例 / 有料＝再現可能な仕組み"),
      ]),
      sideField("proof_material", "使える根拠・素材", "入力されていない実績を作らないため、使える素材を明示します。", "detail", "例：自分で作成したチェックリスト、公開済み記事3本", [
        sideOption("none", "実績・体験談は使わない"), sideOption("own_experience", "自分の実体験あり"),
        sideOption("own_results", "確認済みの自分の実績あり"), sideOption("source_material", "一次資料・公式情報あり"),
        sideOption("existing_content", "既存の記事・教材あり"),
      ], true),
    ],
    promptTemplate: promptLines(
      "あなたは有料コンテンツの商品設計者兼編集者です。",
      "目的は、単なる長文ではなく「購入前に価値が判断でき、購入後に実行できる」コンテンツ商品を設計することです。",
      "",
      "【今回の条件】",
      "販売・掲載先: {{platform}}",
      "商品形態: {{product_type}}",
      "想定購入者: {{buyer_stage}}",
      "購入後に得られる価値: {{value_type}}",
      "無料・有料の境界: {{free_paid_boundary}}",
      "使用可能な根拠・素材: {{proof_material}}",
      "",
      "【必須成果物】",
      "1. この商品の対象者 / 対象外",
      "2. 購入前に無料で伝えるべき内容",
      "3. 有料部分で初めて提供する具体的価値",
      "4. 章構成と各章の「読後に完成するもの」",
      "5. テンプレート・チェックリスト・記入シート等の付属物",
      "6. 販売ページで説明すべき前提条件と注意点",
      "7. 公開前の事実確認チェック",
      "8. 次に記事作成機能へ渡せる執筆ブリーフ",
      "",
      "【禁止】",
      "- 入力されていない売上、販売数、購入者レビュー、実績、体験談を作らない。",
      "- 「必ず稼げる」「誰でも再現」等の成果保証をしない。",
      "- 文字数を増やすための一般論を足さず、購入後に使える成果物を増やす。"
    ),
  },
  {
    slug: "sns-management",
    title: "SNS運用・集客",
    category: "SNS・動画・集客",
    summary: "媒体、アカウント段階、投稿の柱、CTA、検証方法まで一貫した運用設計を作ります。",
    knowledgeTask: "sidejob_sns",
    recommendedAi: "chatgpt",
    fields: [
      sideField("platform", "主に使うSNS", "媒体ごとの閲覧行動に合わせます。", "basic", "例：Bluesky、LinkedIn", [
        sideOption("x", "X"), sideOption("instagram", "Instagram"), sideOption("threads", "Threads"),
        sideOption("tiktok", "TikTok"), sideOption("multi", "複数SNSを連携"),
      ]),
      sideField("account_stage", "アカウントの段階", "新規と既存では優先する施策を変えます。", "basic", "例：半年運用済みだが投稿休止中", [
        sideOption("new", "新規・これから開始"), sideOption("early", "開始1〜3か月"),
        sideOption("active", "継続運用中"), sideOption("restart", "休止から再開"),
        sideOption("pivot", "発信テーマを変更したい"),
      ]),
      sideField("objective", "最優先の目的", "目的を1つに絞って投稿設計を行います。", "basic", "例：イベント申込へ誘導", [
        sideOption("trust", "認知・信頼を増やす"), sideOption("profile", "プロフィール閲覧へつなげる"),
        sideOption("content", "記事・動画へ送る"), sideOption("lead", "相談・問い合わせへつなげる"),
        sideOption("sale", "商品・サービスの検討へつなげる"),
      ]),
      sideField("content_style", "中心にする投稿形式", "継続できる制作負荷も考慮します。", "detail", "例：図解＋短文", [
        sideOption("short_text", "短文・一言"), sideOption("educational", "ノウハウ・解説"),
        sideOption("story", "ストーリー・過程"), sideOption("carousel", "画像・カルーセル"),
        sideOption("short_video", "短尺動画"),
      ]),
      sideField("posting_cycle", "投稿ペース", "無理のない運用単位へ落とします。", "detail", "例：平日だけ週4回", [
        sideOption("daily", "毎日"), sideOption("5_week", "週5回"), sideOption("3_week", "週3回"),
        sideOption("2_week", "週2回"), sideOption("weekly", "週1回"),
      ]),
      sideField("conversion_path", "最終導線", "投稿から次の行動へのつなぎ方を設計します。", "detail", "例：固定投稿→無料相談フォーム", [
        sideOption("profile", "プロフィール内で完結"), sideOption("article", "記事・ブログ"),
        sideOption("video", "YouTube・動画"), sideOption("service", "サービスページ"),
        sideOption("inquiry", "問い合わせ・DM"),
      ], true),
    ],
    promptTemplate: promptLines(
      "あなたはSNS運用設計者です。",
      "単発のバズ狙いではなく、継続投稿・プロフィール・導線・検証をひとつの運用システムとして設計してください。",
      "",
      "【今回の条件】",
      "SNS: {{platform}}",
      "アカウント段階: {{account_stage}}",
      "最優先目的: {{objective}}",
      "中心投稿形式: {{content_style}}",
      "投稿ペース: {{posting_cycle}}",
      "最終導線: {{conversion_path}}",
      "",
      "【必須成果物】",
      "1. アカウントの発信軸を1文で定義",
      "2. 投稿の柱を3〜5本（役割を重複させない）",
      "3. 4週間の投稿配分",
      "4. 各投稿のフック→価値→CTAの型",
      "5. プロフィール・固定投稿との役割分担",
      "6. 投稿ネタ20個",
      "7. 伸びなかった場合に確認する指標と仮説",
      "8. 使い回しではなく媒体に合わせて変える箇所",
      "9. 今週すぐ実行する3タスク",
      "",
      "フォロワー数、表示回数、アルゴリズムの挙動を未確認で断定せず、成果保証はしないでください。"
    ),
  },
  {
    slug: "youtube-video",
    title: "YouTube・ショート動画",
    category: "SNS・動画・集客",
    summary: "企画、フック、台本、撮影・編集、サムネイル、CTAまで動画形式に合わせて作ります。",
    knowledgeTask: "sidejob_video",
    recommendedAi: "claude",
    fields: [
      sideField("format", "動画形式", "尺と視聴行動に合わせて構成を変えます。", "basic", "例：10分前後の解説ライブ切り抜き", [
        sideOption("long", "YouTube長尺"), sideOption("shorts", "YouTube Shorts"),
        sideOption("tiktok", "TikTok短尺"), sideOption("reels", "Instagram Reels"),
        sideOption("live_clip", "配信・ライブ切り抜き"),
      ]),
      sideField("channel_stage", "チャンネル段階", "新規・既存で企画の役割を変えます。", "basic", "例：登録者はいるが新ジャンルへ移行中", [
        sideOption("new", "新規チャンネル"), sideOption("early", "投稿10本未満"),
        sideOption("growing", "継続投稿中"), sideOption("restart", "休止から再開"),
        sideOption("pivot", "ジャンル転換中"),
      ]),
      sideField("video_goal", "この動画の役割", "1本の役割を明確にします。", "basic", "例：新シリーズの導入回", [
        sideOption("discover", "新規視聴者に知ってもらう"), sideOption("educate", "理解・学習を助ける"),
        sideOption("entertain", "楽しんでもらう"), sideOption("trust", "人柄・信頼を伝える"),
        sideOption("convert", "次の動画・商品・相談へつなげる"),
      ]),
      sideField("production_style", "制作スタイル", "撮影・編集負荷に合わせます。", "detail", "例：ゲーム映像＋後付けナレーション", [
        sideOption("talking_head", "顔出し・トーク"), sideOption("voiceover", "ナレーション＋素材"),
        sideOption("screen", "画面収録・解説"), sideOption("gameplay", "ゲーム映像・実況"),
        sideOption("no_face", "顔出しなし"),
      ]),
      sideField("hook_style", "冒頭の型", "内容に合わない煽りは使いません。", "detail", "例：実演結果を最初に見せる", [
        sideOption("result_first", "結論・結果から"), sideOption("problem", "悩み・問題提起から"),
        sideOption("question", "質問から"), sideOption("demo", "実演から"), sideOption("story", "短い出来事から"),
      ]),
      sideField("next_action", "視聴後の行動", "CTAを1つに絞ります。", "detail", "例：関連する再生リストを見てもらう", [
        sideOption("next_video", "次の動画を見る"), sideOption("subscribe", "登録・フォロー"),
        sideOption("comment", "コメント"), sideOption("article", "記事を見る"),
        sideOption("service", "商品・サービスを確認"),
      ]),
    ],
    promptTemplate: promptLines(
      "あなたは動画企画・構成・編集設計の専門家です。",
      "視聴者維持と内容の正確さを両立し、撮影前にそのまま使える制作設計を作ってください。",
      "",
      "【条件】",
      "形式: {{format}}",
      "チャンネル段階: {{channel_stage}}",
      "動画の役割: {{video_goal}}",
      "制作スタイル: {{production_style}}",
      "冒頭の型: {{hook_style}}",
      "視聴後の行動: {{next_action}}",
      "",
      "【必須成果物】",
      "1. 企画の一文要約と「この動画を今見る理由」",
      "2. タイトル案8個（内容にない約束を追加しない）",
      "3. サムネイル文言8個（短く、タイトルと同じ文言にしない）",
      "4. 冒頭0〜15秒の台本",
      "5. 本編のセクション構成と各セクションの視聴維持ポイント",
      "6. 完成台本または話す要点",
      "7. 必要素材・Bロール・画面収録リスト",
      "8. 編集時に削るべき冗長箇所",
      "9. CTA",
      "10. 公開後に確認する指標と、数字ごとの改善仮説",
      "",
      "再生数・登録者増加を保証せず、現在の仕様・アルゴリズムは確認なしに断定しないでください。"
    ),
  },
];
