import type { SideHustleDefinition } from "@/features/side-hustles/types";
import { promptLines, sideField, sideOption } from "@/features/side-hustles/definition-helpers";

export const CLIENT_WORK_SIDE_HUSTLES: readonly SideHustleDefinition[] = [
  {
    slug: "crowdsourcing",
    title: "クラウドソーシング",
    category: "受託・案件獲得",
    summary: "案件要件、自分の事実として使える経験、納期、質問事項を整理して応募から納品まで設計します。",
    knowledgeTask: "sidejob_crowdsourcing",
    recommendedAi: "claude",
    fields: [
      sideField("platform", "案件を探す場所", "応募文の文脈を合わせます。", "basic", "例：企業採用ページ、知人紹介", [
        sideOption("crowdworks", "クラウドワークス"), sideOption("lancers", "ランサーズ"),
        sideOption("coconala", "ココナラ募集"), sideOption("direct", "企業へ直接応募"),
        sideOption("referral", "紹介・コミュニティ"),
      ]),
      sideField("job_type", "案件種別", "成果物・見積もり単位を変えます。", "basic", "例：データ整理、動画字幕", [
        sideOption("writing", "ライティング"), sideOption("design", "デザイン・画像"),
        sideOption("video", "動画編集"), sideOption("sns", "SNS運用"), sideOption("research", "リサーチ・事務"),
      ]),
      sideField("experience", "事実として提示できる経験", "架空の経験を使わないための基準です。", "basic", "例：個人ブログ10本、業務経験はなし", [
        sideOption("none", "未経験"), sideOption("personal", "個人制作経験あり"),
        sideOption("small_paid", "少数の有償案件経験あり"), sideOption("professional", "業務経験あり"),
        sideOption("portfolio", "公開可能なポートフォリオあり"),
      ], true),
      sideField("deadline", "希望する納期感", "無理な約束を避け、確認事項へ反映します。", "detail", "例：初稿5日、修正2日", [
        sideOption("same_day", "当日〜翌日"), sideOption("3_days", "3日程度"),
        sideOption("week", "1週間程度"), sideOption("2_weeks", "2週間程度"),
        sideOption("negotiable", "内容を確認して相談"),
      ]),
      sideField("proposal_style", "応募文の方向性", "案件との適合を中心に文章化します。", "detail", "例：短く質問を中心にした応募", [
        sideOption("concise", "短く要点重視"), sideOption("evidence", "経験・成果物重視"),
        sideOption("process", "進め方・品質管理重視"), sideOption("question", "確認質問重視"),
        sideOption("beginner_honest", "未経験を明示し丁寧に提案"),
      ]),
      sideField("risk", "特に確認したい契約条件", "応募前に曖昧な部分を残さないために使います。", "detail", "例：二次利用と著作権の扱い", [
        sideOption("scope", "作業範囲"), sideOption("revision", "修正回数"),
        sideOption("rights", "権利・公開可否"), sideOption("payment", "報酬・支払条件"),
        sideOption("communication", "連絡頻度・対応時間"),
      ], true),
    ],
    promptTemplate: promptLines(
      "あなたは受託案件の応募・要件整理アシスタントです。",
      "応募を通すために経歴を盛るのではなく、案件要件と実際に提示できる能力を対応付けてください。",
      "",
      "【条件】",
      "案件経路: {{platform}}",
      "案件種別: {{job_type}}",
      "提示できる経験: {{experience}}",
      "納期感: {{deadline}}",
      "応募文の方向性: {{proposal_style}}",
      "重点確認条件: {{risk}}",
      "",
      "【必須成果物】",
      "1. 応募前に案件文から抜き出す要件チェック表",
      "2. 「対応できる / 確認が必要 / 対応不可」の3分類",
      "3. 自分の経験を案件要件へ対応付ける表",
      "4. 応募文（過度な自己PRなし）",
      "5. 応募前に聞く質問",
      "6. 受注後の作業工程",
      "7. 初稿・確認・修正・納品の区切り",
      "8. 認識違いを防ぐ合意事項",
      "9. 納品前チェック",
      "10. 今回の案件を受けるか判断する基準",
      "",
      "入力されていない資格、職歴、案件数、売上、評価、ポートフォリオを作らないでください。"
    ),
  },
  {
    slug: "outreach",
    title: "営業・案件獲得",
    category: "受託・案件獲得",
    summary: "相手に関係する連絡理由、提供価値、提案、質問、フォローアップを押し売りにならない形で作ります。",
    knowledgeTask: "sidejob_outreach",
    recommendedAi: "chatgpt",
    fields: [
      sideField("target", "連絡相手", "相手によって情報量と提案方法を変えます。", "basic", "例：個人で活動する配信者", [
        sideOption("company", "企業"), sideOption("small_business", "小規模事業者"),
        sideOption("creator", "クリエイター"), sideOption("shop", "店舗"),
        sideOption("existing_client", "既存顧客"),
      ]),
      sideField("relationship", "現在の関係", "初回連絡と既存関係を分けます。", "basic", "例：イベントで一度会った", [
        sideOption("cold", "初めて連絡する"), sideOption("follow", "SNS等で相互認知"),
        sideOption("met", "一度会話した"), sideOption("past", "過去に取引あり"),
        sideOption("referral", "紹介を受けた"),
      ]),
      sideField("offer", "提案内容", "提供できることを具体化します。", "basic", "例：YouTubeサムネイル月4枚制作", [
        sideOption("writing", "記事・文章制作"), sideOption("design", "デザイン制作"),
        sideOption("video", "動画関連"), sideOption("sns", "SNS運用"),
        sideOption("support", "設定・業務支援"),
      ], true),
      sideField("channel", "連絡手段", "長さと導入文を調整します。", "detail", "例：問い合わせフォーム", [
        sideOption("email", "メール"), sideOption("dm", "SNS DM"), sideOption("form", "問い合わせフォーム"),
        sideOption("chat", "チャット"), sideOption("proposal", "提案書添付"),
      ]),
      sideField("ask", "最初にお願いすること", "大きな契約ではなく次の一歩を設定します。", "detail", "例：15分のオンライン打合せ", [
        sideOption("reply", "興味があるか返信"), sideOption("call", "短い打合せ"),
        sideOption("brief", "要件を教えてもらう"), sideOption("sample", "サンプル確認"),
        sideOption("quote", "見積条件を確認"),
      ]),
      sideField("followup", "返信がない場合", "しつこい連絡を避けます。", "detail", "例：1週間後に1回だけ再連絡", [
        sideOption("none", "追客しない"), sideOption("once", "1回だけ再連絡"),
        sideOption("two", "最大2回"), sideOption("content", "役立つ情報を添えて再連絡"),
        sideOption("later", "時期を空けて再連絡"),
      ]),
    ],
    promptTemplate: promptLines(
      "あなたはB2B/B2Cの営業文章編集者です。",
      "相手を操作する文章ではなく、「なぜこの相手に連絡したか」「何を提供できるか」「次に何を確認したいか」が短く分かる提案を作ってください。",
      "",
      "【条件】",
      "相手: {{target}}",
      "現在の関係: {{relationship}}",
      "提案内容: {{offer}}",
      "連絡手段: {{channel}}",
      "最初のお願い: {{ask}}",
      "フォロー方針: {{followup}}",
      "",
      "【必須成果物】",
      "1. 連絡前に調べるべき相手情報",
      "2. 相手に関係する仮説と、断定してはいけない部分",
      "3. 件名案（メールの場合）",
      "4. 初回連絡文：短文版",
      "5. 初回連絡文：丁寧版",
      "6. 自分の実績が無い/少ない場合の誠実な言い換え",
      "7. 相手から聞かれやすい質問への回答準備",
      "8. 返信が来た後の確認事項",
      "9. フォローアップ文",
      "10. 連絡を打ち切る基準",
      "",
      "存在しない取引実績、紹介者、導入実績、成果数値を作らないでください。"
    ),
  },
  {
    slug: "sidejob-planner",
    title: "自分に合うAI副業を探す",
    category: "受託・案件獲得",
    summary: "時間、予算、得意分野、営業可否、作りたいものから候補を比較し、30日検証計画を作ります。",
    knowledgeTask: "sidejob_planning",
    recommendedAi: "chatgpt",
    fields: [
      sideField("time", "使える時間", "現実的な検証量を決めます。", "basic", "例：平日30分＋休日3時間", [
        sideOption("3h", "週3時間未満"), sideOption("5h", "週3〜5時間"),
        sideOption("10h", "週5〜10時間"), sideOption("20h", "週10〜20時間"),
        sideOption("20plus", "週20時間以上"),
      ], true),
      sideField("budget", "初期予算", "有料ツールや仕入れの可否を判断します。", "basic", "例：月3,000円まで", [
        sideOption("zero", "0円"), sideOption("3000", "3,000円程度まで"),
        sideOption("10000", "1万円程度まで"), sideOption("30000", "3万円程度まで"),
        sideOption("flex", "必要性を見て判断"),
      ], true),
      sideField("strength", "活かしたい得意分野", "属性ではなく本人が選んだ強みを使います。", "basic", "例：ゲーム知識、接客経験", [
        sideOption("writing", "文章・説明"), sideOption("design", "画像・デザイン"),
        sideOption("video", "動画・配信"), sideOption("research", "調査・整理"),
        sideOption("communication", "相談・コミュニケーション"),
      ], true),
      sideField("sales", "営業への抵抗", "集客方法に影響します。", "detail", "例：文章での営業なら可能", [
        sideOption("avoid", "営業はなるべく避けたい"), sideOption("platform", "プラットフォーム内応募なら可"),
        sideOption("dm", "DM・メール営業も可"), sideOption("call", "打合せ・通話も可"),
        sideOption("active", "積極的に営業できる"),
      ], true),
      sideField("creation", "作りたいもの", "継続しやすい成果物を選びます。", "detail", "例：配信者向け素材", [
        sideOption("content", "記事・コンテンツ"), sideOption("sns", "SNS投稿"),
        sideOption("video", "動画"), sideOption("product", "商品・テンプレート"),
        sideOption("service", "人に提供するサービス"),
      ], true),
      sideField("risk", "重視すること", "候補の選び方を調整します。", "detail", "例：少額でも継続しやすさ優先", [
        sideOption("low_cost", "初期費用を抑える"), sideOption("simple", "作業をシンプルにする"),
        sideOption("repeat", "継続収入につながる形を目指す"), sideOption("skill", "スキル蓄積を優先"),
        sideOption("test", "小さく試して判断"),
      ], true),
    ],
    promptTemplate: promptLines(
      "あなたは副業の選択肢を整理するプランナーです。",
      "ユーザーの属性から向き不向きを決めつけず、本人が入力した時間・予算・得意・営業可否・制作物の好みだけを使って候補を比較してください。",
      "",
      "【条件】",
      "使える時間: {{time}}",
      "初期予算: {{budget}}",
      "得意分野: {{strength}}",
      "営業への抵抗: {{sales}}",
      "作りたいもの: {{creation}}",
      "重視すること: {{risk}}",
      "",
      "【必須成果物】",
      "1. 条件から見た制約と強み",
      "2. 候補を5つ（候補ごとに仕事内容を具体化）",
      "3. 各候補の「最初に作る成果物」",
      "4. 必要な準備・ツール・確認事項",
      "5. 営業・集客の方法",
      "6. 収益ではなく、30日で確認できる検証指標",
      "7. 1〜4週目の行動計画",
      "8. 続ける / 修正する / やめる判断基準",
      "9. 最初に選ぶ候補を決めるための比較表",
      "10. 選んだ候補をAASのどの専用機能で進めるか",
      "",
      "収益額、成功確率、案件獲得を保証せず、実在案件数や相場を最新確認なしに断定しないでください。"
    ),
  },
];
