-- Phase 66: auditable source recheck receipts.
-- A source freshness date advances only after every currently configured source URL
-- has a newer admin receipt whose latest outcome is "unchanged".
-- Changed/unreachable/removed outcomes keep the old freshness date and open a Fresh follow-up.

create table if not exists public.knowledge_source_recheck_receipts (
  id bigint generated by default as identity primary key,
  item_type text not null check (item_type in ('knowledge','prompt')),
  item_key text not null,
  catalog_version bigint not null check (catalog_version >= 1),
  source_url text not null,
  outcome text not null check (outcome in ('unchanged','changed','unreachable','removed')),
  notes text not null default '',
  request_id bigint null references public.knowledge_refresh_requests(id) on delete set null,
  checked_by uuid not null references auth.users(id) on delete restrict,
  checked_at timestamptz not null default now(),
  completed_cycle boolean not null default false,
  created_at timestamptz not null default now(),
  constraint knowledge_source_recheck_receipts_https
    check (source_url ~* '^https://')
);

create index if not exists knowledge_source_recheck_receipts_item_idx
  on public.knowledge_source_recheck_receipts (item_type,item_key,checked_at desc,id desc);

create index if not exists knowledge_source_recheck_receipts_request_idx
  on public.knowledge_source_recheck_receipts (request_id)
  where request_id is not null;

alter table public.knowledge_source_recheck_receipts enable row level security;
revoke all on table public.knowledge_source_recheck_receipts from public, anon, authenticated;


create or replace function public.admin_record_knowledge_source_recheck_receipt(
  p_item_type text,
  p_item_key text,
  p_source_url text,
  p_outcome text,
  p_notes text default '',
  p_request_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare
  item_type_value text := lower(trim(coalesce(p_item_type,'')));
  item_key_value text := trim(coalesce(p_item_key,''));
  source_url_value text := trim(coalesce(p_source_url,''));
  outcome_value text := lower(trim(coalesce(p_outcome,'')));
  notes_value text := left(trim(coalesce(p_notes,'')),1000);
  source_urls_value text[];
  baseline_checked_at timestamptz;
  item_version bigint;
  receipt_id bigint;
  total_sources integer := 0;
  checked_sources integer := 0;
  completed_cycle_value boolean := false;
  followup_request_id bigint := null;
begin
  if (select auth.uid()) is null
     or not (select private.is_active_admin())
  then
    raise exception 'active admin required' using errcode='42501';
  end if;

  if item_type_value not in ('knowledge','prompt') then
    raise exception 'invalid item type' using errcode='22023';
  end if;
  if item_key_value = '' then
    raise exception 'item key is required' using errcode='22023';
  end if;
  if source_url_value !~* '^https://' then
    raise exception 'https source URL is required' using errcode='22023';
  end if;
  if outcome_value not in ('unchanged','changed','unreachable','removed') then
    raise exception 'invalid source outcome' using errcode='22023';
  end if;

  if item_type_value = 'knowledge' then
    select item.source_urls,item.source_checked_at,item.catalog_version
    into source_urls_value,baseline_checked_at,item_version
    from public.knowledge_catalog item
    where item.key=item_key_value
      and item.status='active';
  else
    select item.source_urls,item.source_checked_at,item.catalog_version
    into source_urls_value,baseline_checked_at,item_version
    from public.prompt_optimization_catalog item
    where item.key=item_key_value
      and item.status='active';
  end if;

  if not found then
    raise exception 'active source item not found' using errcode='P0002';
  end if;

  source_urls_value := coalesce(source_urls_value,array[]::text[]);
  if not (source_url_value = any(source_urls_value)) then
    raise exception 'source URL is not registered on this item' using errcode='22023';
  end if;

  if p_request_id is not null
     and not exists (
       select 1
       from public.knowledge_refresh_requests request
       where request.id=p_request_id
     )
  then
    raise exception 'refresh request not found' using errcode='P0002';
  end if;

  insert into public.knowledge_source_recheck_receipts (
    item_type,item_key,catalog_version,source_url,outcome,notes,
    request_id,checked_by,checked_at,completed_cycle
  ) values (
    item_type_value,item_key_value,item_version,source_url_value,outcome_value,notes_value,
    p_request_id,(select auth.uid()),now(),false
  )
  returning id into receipt_id;

  select
    count(*)::integer,
    count(*) filter (where latest_outcome='unchanged')::integer
  into total_sources,checked_sources
  from (
    select
      source.url,
      (
        select receipt.outcome
        from public.knowledge_source_recheck_receipts receipt
        where receipt.item_type=item_type_value
          and receipt.item_key=item_key_value
          and receipt.source_url=source.url
          and receipt.checked_at > coalesce(baseline_checked_at,'1970-01-01 00:00:00+00'::timestamptz)
        order by receipt.checked_at desc,receipt.id desc
        limit 1
      ) as latest_outcome
    from unnest(source_urls_value) as source(url)
  ) latest;

  if outcome_value='unchanged'
     and total_sources > 0
     and checked_sources = total_sources
  then
    if item_type_value='knowledge' then
      update public.knowledge_catalog
      set source_checked_at=now(),updated_at=now()
      where key=item_key_value and status='active';
    else
      update public.prompt_optimization_catalog
      set source_checked_at=now(),updated_at=now()
      where key=item_key_value and status='active';
    end if;

    completed_cycle_value := true;
    update public.knowledge_source_recheck_receipts
    set completed_cycle=true
    where id=receipt_id;
  end if;

  if outcome_value in ('changed','unreachable','removed') then
    if p_request_id is not null then
      select request.id
      into followup_request_id
      from public.knowledge_refresh_requests request
      where request.id=p_request_id
        and request.channel='fresh'
        and request.status in ('pending','processing');
    end if;

    if followup_request_id is null then
      select request.id
      into followup_request_id
      from public.knowledge_refresh_requests request
      where request.channel='fresh'
        and request.status in ('pending','processing')
      order by request.id desc
      limit 1;
    end if;

    if followup_request_id is null then
      insert into public.knowledge_refresh_requests (
        channel,research_summary
      ) values (
        'fresh',
        'Source recheck requires follow-up: ' || item_type_value || ' ' || item_key_value
      )
      returning id into followup_request_id;

      update public.knowledge_refresh_channels channel
      set
        last_refresh_requested_at=now(),
        next_refresh_due_at=now()+make_interval(hours=>channel.refresh_hours),
        updated_at=now()
      where channel.channel='fresh';
    end if;
  end if;

  return jsonb_build_object(
    'receipt_id',receipt_id,
    'item_type',item_type_value,
    'item_key',item_key_value,
    'outcome',outcome_value,
    'checked_source_count',checked_sources,
    'total_source_count',total_sources,
    'remaining_source_count',greatest(total_sources-checked_sources,0),
    'completed_cycle',completed_cycle_value,
    'followup_request_id',followup_request_id
  );
end;
$function$;

revoke all on function public.admin_record_knowledge_source_recheck_receipt(text,text,text,text,text,bigint)
from public, anon;
grant execute on function public.admin_record_knowledge_source_recheck_receipt(text,text,text,text,text,bigint)
to authenticated;


create or replace function public.admin_list_knowledge_source_recheck_receipts(
  p_limit integer default 30
)
returns table (
  id bigint,
  item_type text,
  item_key text,
  catalog_version bigint,
  source_url text,
  outcome text,
  notes text,
  request_id bigint,
  checked_at timestamptz,
  completed_cycle boolean
)
language plpgsql
stable
security definer
set search_path to ''
as $function$
declare
  limit_value integer := greatest(1,least(coalesce(p_limit,30),100));
begin
  if (select auth.uid()) is null
     or not (select private.is_active_admin())
  then
    raise exception 'active admin required' using errcode='42501';
  end if;

  return query
  select
    receipt.id,
    receipt.item_type,
    receipt.item_key,
    receipt.catalog_version,
    receipt.source_url,
    receipt.outcome,
    receipt.notes,
    receipt.request_id,
    receipt.checked_at,
    receipt.completed_cycle
  from public.knowledge_source_recheck_receipts receipt
  order by receipt.checked_at desc,receipt.id desc
  limit limit_value;
end;
$function$;

revoke all on function public.admin_list_knowledge_source_recheck_receipts(integer)
from public, anon;
grant execute on function public.admin_list_knowledge_source_recheck_receipts(integer)
to authenticated;
