-- Automatic official-source monitoring for AAS Knowledge / Prompt.
-- Research and candidate generation are automatic; final publication remains admin-review gated.

create table if not exists public.knowledge_automation_settings (
  id smallint primary key default 1 check (id = 1),
  enabled boolean not null default true,
  check_interval_hours integer not null default 24 check (check_interval_hours between 1 and 168),
  max_sources_per_run integer not null default 12 check (max_sources_per_run between 1 and 30),
  max_discovered_links_per_source integer not null default 6 check (max_discovered_links_per_source between 0 and 20),
  project_url text not null,
  worker_token_hash text not null default '',
  last_worker_invoked_at timestamptz,
  last_success_at timestamptz,
  last_error text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_automation_sources (
  id bigint generated by default as identity primary key,
  source_url text not null unique check (source_url ~* '^https://[^[:space:]]+$'),
  tasks text[] not null default '{}',
  source_kind text not null default 'official_page'
    check (source_kind in ('official_page','official_help','official_policy','official_docs','official_changelog','official_feed')),
  enabled boolean not null default true,
  last_checked_at timestamptz,
  next_check_at timestamptz not null default now(),
  last_http_status integer,
  last_content_hash text,
  etag text,
  last_modified text,
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_automation_runs (
  id bigint generated by default as identity primary key,
  trigger_type text not null default 'cron' check (trigger_type in ('cron','manual')),
  status text not null default 'pending' check (status in ('pending','processing','completed','failed','cancelled')),
  requested_by uuid references auth.users(id) on delete set null,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  sources_checked integer not null default 0,
  candidates_created integer not null default 0,
  changed_sources integer not null default 0,
  discovered_links integer not null default 0,
  error_message text not null default '',
  summary jsonb not null default '{}'::jsonb
);

create table if not exists public.knowledge_automation_candidates (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  run_id bigint references public.knowledge_automation_runs(id) on delete set null,
  source_id bigint references public.knowledge_automation_sources(id) on delete set null,
  candidate_action text not null check (candidate_action in ('new','update','recheck','retire')),
  existing_item_type text check (existing_item_type is null or existing_item_type in ('knowledge','prompt')),
  existing_item_key text,
  matched_tasks text[] not null default '{}',
  source_url text not null check (source_url ~* '^https://[^[:space:]]+$'),
  source_title text not null default '',
  source_excerpt text not null default '',
  source_content_hash text not null default '',
  source_http_status integer,
  current_payload jsonb,
  proposed_payload jsonb,
  research_prompt text not null default '',
  confidence smallint not null default 50 check (confidence between 0 and 100),
  reason text not null default '',
  status text not null default 'pending' check (status in ('pending','approved','rejected','converted')),
  review_notes text not null default '',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  detected_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists knowledge_automation_sources_due_idx
  on public.knowledge_automation_sources (enabled, next_check_at, id);

create index if not exists knowledge_automation_runs_status_idx
  on public.knowledge_automation_runs (status, requested_at desc);

create index if not exists knowledge_automation_candidates_status_idx
  on public.knowledge_automation_candidates (status, detected_at desc);

create index if not exists knowledge_automation_candidates_existing_idx
  on public.knowledge_automation_candidates (existing_item_type, existing_item_key)
  where existing_item_key is not null;

alter table public.knowledge_automation_settings enable row level security;
alter table public.knowledge_automation_sources enable row level security;
alter table public.knowledge_automation_runs enable row level security;
alter table public.knowledge_automation_candidates enable row level security;

revoke all on table public.knowledge_automation_settings from anon, authenticated;
revoke all on table public.knowledge_automation_sources from anon, authenticated;
revoke all on table public.knowledge_automation_runs from anon, authenticated;
revoke all on table public.knowledge_automation_candidates from anon, authenticated;

grant select, insert, update, delete on table public.knowledge_automation_settings to service_role;
grant select, insert, update, delete on table public.knowledge_automation_sources to service_role;
grant select, insert, update, delete on table public.knowledge_automation_runs to service_role;
grant select, insert, update, delete on table public.knowledge_automation_candidates to service_role;
grant usage, select on sequence public.knowledge_automation_sources_id_seq to service_role;
grant usage, select on sequence public.knowledge_automation_runs_id_seq to service_role;
grant usage, select on sequence public.knowledge_automation_candidates_id_seq to service_role;

insert into public.knowledge_automation_settings (
  id, enabled, check_interval_hours, max_sources_per_run, max_discovered_links_per_source, project_url
) values (
  1, true, 24, 12, 6, 'https://nwttfmjsgzpjqqubxbff.supabase.co'
)
on conflict (id) do update set
  project_url = excluded.project_url,
  updated_at = now();

do $migration$
declare
  worker_token text;
begin
  select decrypted_secret
    into worker_token
  from vault.decrypted_secrets
  where name = 'aas_knowledge_worker_token'
  limit 1;

  if worker_token is null or worker_token = '' then
    worker_token := encode(extensions.gen_random_bytes(32), 'hex');
    perform vault.create_secret(
      worker_token,
      'aas_knowledge_worker_token',
      'AAS Knowledge automation Edge Function authentication token'
    );
  end if;

  update public.knowledge_automation_settings
  set
    worker_token_hash = encode(extensions.digest(worker_token, 'sha256'), 'hex'),
    updated_at = now()
  where id = 1;
end
$migration$;

with source_rows as (
  select trim(source_url) as source_url, task
  from public.knowledge_catalog as catalog
  cross join lateral unnest(coalesce(catalog.source_urls, array[]::text[])) as source_url
  left join lateral unnest(
    case when cardinality(catalog.tasks) > 0 then catalog.tasks else array['all']::text[] end
  ) as task on true
  where catalog.status = 'active'
    and source_url ~* '^https://[^[:space:]]+$'

  union all

  select trim(source_url) as source_url, coalesce(nullif(catalog.task,''),'all') as task
  from public.prompt_optimization_catalog as catalog
  cross join lateral unnest(coalesce(catalog.source_urls, array[]::text[])) as source_url
  where catalog.status = 'active'
    and source_url ~* '^https://[^[:space:]]+$'
),
grouped as (
  select source_url,
    array_agg(distinct coalesce(task,'all') order by coalesce(task,'all')) as tasks
  from source_rows
  group by source_url
)
insert into public.knowledge_automation_sources (source_url, tasks, enabled, next_check_at)
select source_url, tasks, true, now()
from grouped
on conflict (source_url) do update set
  tasks = excluded.tasks,
  enabled = true,
  updated_at = now();

create or replace function public.admin_get_knowledge_automation_status()
returns table (
  enabled boolean,
  check_interval_hours integer,
  max_sources_per_run integer,
  tracked_sources integer,
  due_sources integer,
  pending_candidates integer,
  approved_candidates integer,
  last_worker_invoked_at timestamptz,
  last_success_at timestamptz,
  last_error text,
  latest_run_id bigint,
  latest_run_status text,
  latest_run_started_at timestamptz,
  latest_run_completed_at timestamptz,
  latest_run_sources_checked integer,
  latest_run_candidates_created integer
)
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if (select auth.uid()) is null or not (select private.is_active_admin()) then
    raise exception 'active admin required' using errcode='42501';
  end if;

  return query
  select
    settings.enabled,
    settings.check_interval_hours,
    settings.max_sources_per_run,
    (select count(*)::integer from public.knowledge_automation_sources source where source.enabled),
    (select count(*)::integer from public.knowledge_automation_sources source where source.enabled and source.next_check_at <= now()),
    (select count(*)::integer from public.knowledge_automation_candidates candidate where candidate.status='pending'),
    (select count(*)::integer from public.knowledge_automation_candidates candidate where candidate.status='approved'),
    settings.last_worker_invoked_at,
    settings.last_success_at,
    settings.last_error,
    run.id,
    run.status,
    run.started_at,
    run.completed_at,
    coalesce(run.sources_checked,0),
    coalesce(run.candidates_created,0)
  from public.knowledge_automation_settings settings
  left join lateral (
    select *
    from public.knowledge_automation_runs r
    order by r.id desc
    limit 1
  ) run on true
  where settings.id=1;
end;
$function$;

create or replace function public.admin_list_knowledge_automation_candidates(
  p_status text default 'pending',
  p_limit integer default 50
)
returns table (
  id bigint,
  candidate_action text,
  existing_item_type text,
  existing_item_key text,
  matched_tasks text[],
  source_url text,
  source_title text,
  source_excerpt text,
  source_http_status integer,
  current_payload jsonb,
  proposed_payload jsonb,
  research_prompt text,
  confidence smallint,
  reason text,
  status text,
  review_notes text,
  detected_at timestamptz,
  reviewed_at timestamptz
)
language plpgsql
security definer
set search_path to ''
as $function$
declare
  status_value text := nullif(lower(trim(coalesce(p_status,''))),'');
  limit_value integer := greatest(1,least(coalesce(p_limit,50),200));
begin
  if (select auth.uid()) is null or not (select private.is_active_admin()) then
    raise exception 'active admin required' using errcode='42501';
  end if;
  if status_value is not null and status_value not in ('pending','approved','rejected','converted') then
    raise exception 'invalid automation candidate status' using errcode='22023';
  end if;

  return query
  select
    candidate.id, candidate.candidate_action, candidate.existing_item_type,
    candidate.existing_item_key, candidate.matched_tasks, candidate.source_url,
    candidate.source_title, candidate.source_excerpt, candidate.source_http_status,
    candidate.current_payload, candidate.proposed_payload, candidate.research_prompt,
    candidate.confidence, candidate.reason, candidate.status, candidate.review_notes,
    candidate.detected_at, candidate.reviewed_at
  from public.knowledge_automation_candidates candidate
  where status_value is null or candidate.status=status_value
  order by
    case candidate.status when 'pending' then 0 when 'approved' then 1 when 'rejected' then 2 else 3 end,
    candidate.confidence desc,
    candidate.detected_at desc
  limit limit_value;
end;
$function$;

create or replace function public.admin_review_knowledge_automation_candidate(
  p_candidate_id bigint,
  p_decision text,
  p_notes text default ''
)
returns void
language plpgsql
security definer
set search_path to ''
as $function$
declare
  decision_value text := lower(trim(coalesce(p_decision,'')));
begin
  if (select auth.uid()) is null or not (select private.is_active_admin()) then
    raise exception 'active admin required' using errcode='42501';
  end if;
  if decision_value not in ('approved','rejected','converted') then
    raise exception 'decision must be approved, rejected, or converted' using errcode='22023';
  end if;

  update public.knowledge_automation_candidates
  set
    status=decision_value,
    review_notes=left(coalesce(p_notes,''),2000),
    reviewed_by=(select auth.uid()),
    reviewed_at=now()
  where id=p_candidate_id;

  if not found then
    raise exception 'automation candidate not found' using errcode='P0002';
  end if;
end;
$function$;

create or replace function public.admin_request_knowledge_automation_run()
returns bigint
language plpgsql
security definer
set search_path to ''
as $function$
declare
  run_id bigint;
begin
  if (select auth.uid()) is null or not (select private.is_active_admin()) then
    raise exception 'active admin required' using errcode='42501';
  end if;

  if exists (
    select 1 from public.knowledge_automation_runs
    where status in ('pending','processing')
  ) then
    select id into run_id
    from public.knowledge_automation_runs
    where status in ('pending','processing')
    order by id desc limit 1;
    return run_id;
  end if;

  insert into public.knowledge_automation_runs (trigger_type,status,requested_by)
  values ('manual','pending',(select auth.uid()))
  returning id into run_id;

  return run_id;
end;
$function$;

revoke all on function public.admin_get_knowledge_automation_status() from public, anon, authenticated;
revoke all on function public.admin_list_knowledge_automation_candidates(text,integer) from public, anon, authenticated;
revoke all on function public.admin_review_knowledge_automation_candidate(bigint,text,text) from public, anon, authenticated;
revoke all on function public.admin_request_knowledge_automation_run() from public, anon, authenticated;

grant execute on function public.admin_get_knowledge_automation_status() to authenticated;
grant execute on function public.admin_list_knowledge_automation_candidates(text,integer) to authenticated;
grant execute on function public.admin_review_knowledge_automation_candidate(bigint,text,text) to authenticated;
grant execute on function public.admin_request_knowledge_automation_run() to authenticated;
